### ISSUE TITLE
Spaces in scripts path raise Error

### ISSUE THREAD

**Issue by vinzw** [tokejepsen/atom-foundry-nuke#3]
If the script is saved in a path with a space, this error is raised:

Traceback (most recent call last):
File "<string>", line 14, in <module>
IOError: [Errno 2] No such file or directory: 'path with spaces'

I know it's stupid to have spaces in a folder name, but unfortunately, that's how "Google\ Drive" is set up.
I like to store my scripts in my Gdrive because it's an easy way to work from home and at work seamlessly...
It would be nice if this can be fixed, not a top priority, though.

**Comment by tokejepsen** [comment]
Thank you for this report, will have a look as soon possible.
